package generation

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/01JAMIL/supago.git/internal/introspection"
)

func GenerateCRUD(schema *introspection.Schema, modulePath string) error {
	modelsPkg := modulePath + "/internal/adapters/supago"
	jsonPkg := modulePath + "/internal/json"

	if err := writeJSONUtil(jsonPkg); err != nil {
		return err
	}

	for _, table := range schema.Tables {
		tableDir := filepath.Join("internal", table.Name)
		if err := os.MkdirAll(tableDir, 0755); err != nil {
			return fmt.Errorf("create directory for %s: %w", table.Name, err)
		}

		if err := writeService(tableDir, table, modelsPkg, modulePath); err != nil {
			return err
		}
		if err := writeHandler(tableDir, table, modelsPkg, modulePath); err != nil {
			return err
		}
	}
	return nil
}

func writeJSONUtil(jsonPkg string) error {
	var b strings.Builder
	b.WriteString("// Code generated by SupaGo. DO NOT EDIT.\n")
	b.WriteString("package json\n\n")
	b.WriteString("import (\n\t\"encoding/json\"\n\t\"net/http\"\n)\n\n")
	b.WriteString("func Write(w http.ResponseWriter, status int, data any) {\n")
	b.WriteString("\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
	b.WriteString("\tw.WriteHeader(status)\n")
	b.WriteString("\tif err := json.NewEncoder(w).Encode(data); err != nil {\n")
	b.WriteString("\t\tpanic(err)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
	b.WriteString("func Read(r *http.Request, data any) error {\n")
	b.WriteString("\tdecoder := json.NewDecoder(r.Body)\n")
	b.WriteString("\tdecoder.DisallowUnknownFields()\n")
	b.WriteString("\treturn decoder.Decode(data)\n")
	b.WriteString("}\n")

	path := filepath.Join("internal", "json", "json.go")
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return formatAndWrite(path, b.String())
}

func writeService(dir string, table introspection.Table, modelsPkg, modulePath string) error {
	structName := toPascalCase(singularize(table.Name))
	pkgBase := filepath.Base(modelsPkg)
	singular := singularize(table.Name)
	repoAlias := table.Name + "repo"
	repoPkg := modulePath + "/internal/adapters/supago/" + table.Name

	var pkCol *introspection.Column
	for _, c := range table.Columns {
		if c.PrimaryKey {
			pkCol = &c
			break
		}
	}

	var b strings.Builder
	b.WriteString("// Generated by SupaGo as a starting point. Modify as needed.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", table.Name))
	b.WriteString("import (\n\t\"context\"\n")
	b.WriteString(fmt.Sprintf("\t\"%s\"\n", modelsPkg))
	b.WriteString(fmt.Sprintf("\t%s \"%s\"\n", repoAlias, repoPkg))
	b.WriteString(")\n\n")
	b.WriteString(fmt.Sprintf("type Service struct {\n\trepo *%s.Repository\n}\n\n", repoAlias))
	b.WriteString(fmt.Sprintf("func NewService(repo *%s.Repository) *Service {\n\treturn &Service{repo: repo}\n}\n\n", repoAlias))
	b.WriteString(fmt.Sprintf("func (s *Service) List(ctx context.Context) ([]%s.%s, error) {\n\treturn s.repo.List(ctx)\n}\n\n", pkgBase, structName))

	if pkCol != nil {
		pkType := toGoType(pkCol.DataType, false)
		b.WriteString(fmt.Sprintf("func (s *Service) GetByID(ctx context.Context, id %s) (*%s.%s, error) {\n\treturn s.repo.GetByID(ctx, id)\n}\n\n", pkType, pkgBase, structName))
	}

	b.WriteString(fmt.Sprintf("func (s *Service) Create(ctx context.Context, %s *%s.%s) error {\n\treturn s.repo.Create(ctx, %s)\n}\n\n", singular, pkgBase, structName, singular))

	if pkCol != nil {
		b.WriteString(fmt.Sprintf("func (s *Service) Update(ctx context.Context, %s *%s.%s) error {\n\treturn s.repo.Update(ctx, %s)\n}\n\n", singular, pkgBase, structName, singular))
		pkType := toGoType(pkCol.DataType, false)
		b.WriteString(fmt.Sprintf("func (s *Service) Delete(ctx context.Context, id %s) error {\n\treturn s.repo.Delete(ctx, id)\n}\n", pkType))
	}

	return formatAndWrite(filepath.Join(dir, "service.go"), b.String())
}

func writeHandler(dir string, table introspection.Table, modelsPkg, modulePath string) error {
	structName := toPascalCase(singularize(table.Name))
	pkgBase := filepath.Base(modelsPkg)
	jsonPkg := modulePath + "/internal/json"

	var pkCol *introspection.Column
	for _, c := range table.Columns {
		if c.PrimaryKey {
			pkCol = &c
			break
		}
	}

	var b strings.Builder
	b.WriteString("// Generated by SupaGo as a starting point. Modify as needed.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", table.Name))
	b.WriteString("import (\n")
	b.WriteString("\t\"net/http\"\n")
	if pkCol != nil && baseGoType(pkCol.DataType) == "int64" {
		b.WriteString("\t\"strconv\"\n")
	}
	b.WriteString(fmt.Sprintf("\t\"%s\"\n", modelsPkg))
	b.WriteString(fmt.Sprintf("\t\"%s\"\n", jsonPkg))
	b.WriteString(")\n\n")

	b.WriteString("type Handler struct {\n\tsvc *Service\n}\n\n")
	b.WriteString("func NewHandler(svc *Service) *Handler {\n\treturn &Handler{svc: svc}\n}\n\n")

	// List
	b.WriteString("func (h *Handler) List(w http.ResponseWriter, r *http.Request) {\n")
	b.WriteString("\tctx := r.Context()\n")
	b.WriteString("\titems, err := h.svc.List(ctx)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)\n")
	b.WriteString("\t\treturn\n")
	b.WriteString("\t}\n")
	b.WriteString("\tjson.Write(w, http.StatusOK, items)\n")
	b.WriteString("}\n\n")

	// GetByID
	if pkCol != nil {
		b.WriteString("func (h *Handler) GetByID(w http.ResponseWriter, r *http.Request) {\n")
		handlerWriteIDParse(&b, pkCol)
		b.WriteString("\tctx := r.Context()\n")
		b.WriteString("\titem, err := h.svc.GetByID(ctx, id)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)\n")
		b.WriteString("\t\treturn\n")
		b.WriteString("\t}\n")
		b.WriteString("\tjson.Write(w, http.StatusOK, item)\n")
		b.WriteString("}\n\n")
	}

	// Create
	b.WriteString("func (h *Handler) Create(w http.ResponseWriter, r *http.Request) {\n")
	b.WriteString(fmt.Sprintf("\tvar item %s.%s\n", pkgBase, structName))
	b.WriteString("\tif err := json.Read(r, &item); err != nil {\n")
	b.WriteString("\t\thttp.Error(w, \"invalid request body\", http.StatusBadRequest)\n")
	b.WriteString("\t\treturn\n")
	b.WriteString("\t}\n")
	b.WriteString("\tctx := r.Context()\n")
	b.WriteString(fmt.Sprintf("\tif err := h.svc.Create(ctx, &item); err != nil {\n"))
	b.WriteString("\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)\n")
	b.WriteString("\t\treturn\n")
	b.WriteString("\t}\n")
	b.WriteString("\tjson.Write(w, http.StatusCreated, item)\n")
	b.WriteString("}\n\n")

	// Update
	if pkCol != nil {
		pkField := toPascalCase(pkCol.Name)

		b.WriteString("func (h *Handler) Update(w http.ResponseWriter, r *http.Request) {\n")
		handlerWriteIDParse(&b, pkCol)
		b.WriteString(fmt.Sprintf("\tvar item %s.%s\n", pkgBase, structName))
		b.WriteString("\tif err := json.Read(r, &item); err != nil {\n")
		b.WriteString("\t\thttp.Error(w, \"invalid request body\", http.StatusBadRequest)\n")
		b.WriteString("\t\treturn\n")
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\titem.%s = id\n", pkField))
		b.WriteString("\tctx := r.Context()\n")
		b.WriteString(fmt.Sprintf("\tif err := h.svc.Update(ctx, &item); err != nil {\n"))
		b.WriteString("\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)\n")
		b.WriteString("\t\treturn\n")
		b.WriteString("\t}\n")
		b.WriteString("\tjson.Write(w, http.StatusOK, item)\n")
		b.WriteString("}\n\n")
	}

	// Delete
	if pkCol != nil {
		b.WriteString("func (h *Handler) Delete(w http.ResponseWriter, r *http.Request) {\n")
		handlerWriteIDParse(&b, pkCol)
		b.WriteString("\tctx := r.Context()\n")
		b.WriteString("\tif err := h.svc.Delete(ctx, id); err != nil {\n")
		b.WriteString("\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)\n")
		b.WriteString("\t\treturn\n")
		b.WriteString("\t}\n")
		b.WriteString("\tjson.Write(w, http.StatusNoContent, nil)\n")
		b.WriteString("}\n")
	}

	return formatAndWrite(filepath.Join(dir, "handler.go"), b.String())
}

func handlerWriteIDParse(b *strings.Builder, pkCol *introspection.Column) {
	pkGoType := baseGoType(pkCol.DataType)
	if pkGoType == "int64" {
		b.WriteString("\tid, err := strconv.ParseInt(r.PathValue(\"id\"), 10, 64)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\thttp.Error(w, \"invalid id\", http.StatusBadRequest)\n")
		b.WriteString("\t\treturn\n")
		b.WriteString("\t}\n")
	} else if pkGoType == "string" {
		b.WriteString("\tid := r.PathValue(\"id\")\n")
	}
}

func formatAndWrite(path, source string) error {
	src, err := format.Source([]byte(source))
	if err != nil {
		return fmt.Errorf("format source: %w", err)
	}
	return os.WriteFile(path, src, 0644)
}
