package generation

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/01JAMIL/supago.git/internal/introspection"
)

func GenerateModels(schema *introspection.Schema, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	path := filepath.Join(outputDir, "models.go")

	var b strings.Builder

	b.WriteString("// Code generated by SupaGo. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", filepath.Base(outputDir)))

	needsTime := false
	needsJSON := false
	for _, table := range schema.Tables {
		for _, col := range table.Columns {
			if needsTimeImport(col.DataType) {
				needsTime = true
			}
			if col.DataType == "json" || col.DataType == "jsonb" {
				needsJSON = true
			}
		}
	}

	if needsTime || needsJSON {
		b.WriteString("import (\n")
		if needsTime {
			b.WriteString("\t\"time\"\n")
		}
		if needsJSON {
			b.WriteString("\t\"encoding/json\"\n")
		}
		b.WriteString(")\n\n")
	}

	for _, table := range schema.Tables {
		structName := toPascalCase(singularize(table.Name))
		b.WriteString(fmt.Sprintf("type %s struct {\n", structName))
		for _, col := range table.Columns {
			goType := toGoType(col.DataType, col.Nullable)
			fieldName := toPascalCase(col.Name)
			jsonTag := toCamelCase(col.Name)
			b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", fieldName, goType, jsonTag))
		}
		b.WriteString("}\n\n")
	}

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("format source: %w", err)
	}
	return os.WriteFile(path, src, 0644)
}

func singularize(name string) string {
	if strings.HasSuffix(name, "s") {
		return strings.TrimSuffix(name, "s")
	}
	return name
}

func toPascalCase(name string) string {
	parts := strings.Split(name, "_")
	for i, p := range parts {
		if strings.ToLower(p) == "id" {
			parts[i] = "ID"
		} else {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func toCamelCase(name string) string {
	parts := strings.Split(name, "_")
	for i, p := range parts {
		if i == 0 {
			parts[i] = strings.ToLower(p)
		} else {
			if strings.ToLower(p) == "id" {
				parts[i] = "ID"
			} else {
				parts[i] = strings.ToUpper(p[:1]) + p[1:]
			}
		}
	}
	return strings.Join(parts, "")
}

func needsTimeImport(pgType string) bool {
	switch pgType {
	case "timestamp with time zone", "timestamp without time zone", "date":
		return true
	}
	return false
}

func toGoType(pgType string, nullable bool) string {
	base := baseGoType(pgType)
	if nullable && base != "time.Time" && base != "json.RawMessage" {
		return "*" + base
	}
	return base
}

func baseGoType(pgType string) string {
	switch pgType {
	case "integer", "bigint", "smallint":
		return "int64"
	case "boolean":
		return "bool"
	case "character varying", "character", "text", "uuid":
		return "string"
	case "timestamp with time zone", "timestamp without time zone", "date":
		return "time.Time"
	case "real", "double precision", "numeric":
		return "float64"
	case "json", "jsonb":
		return "json.RawMessage"
	default:
		if strings.HasPrefix(pgType, "timestamp") {
			return "time.Time"
		}
		return "string"
	}
}
