package generation

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/01JAMIL/supago.git/internal/introspection"
)

func GenerateRepositories(schema *introspection.Schema, outputDir, modulePath string) error {
	modelsPkg := modulePath + "/" + outputDir

	for _, table := range schema.Tables {
		tableDir := filepath.Join(outputDir, table.Name)
		if err := os.MkdirAll(tableDir, 0755); err != nil {
			return fmt.Errorf("create directory for %s: %w", table.Name, err)
		}

		if err := writeRepositoryFile(tableDir, table, modelsPkg); err != nil {
			return fmt.Errorf("generate repository for %s: %w", table.Name, err)
		}
	}
	return nil
}

func writeRepositoryFile(dir string, table introspection.Table, modelsPkg string) error {
	structName := toPascalCase(singularize(table.Name))
	path := filepath.Join(dir, "repository.go")

	cols := table.Columns
	colNames := columnNames(cols)
	colFields := columnFields(cols)

	var pkCol *introspection.Column
	for _, c := range cols {
		if c.PrimaryKey {
			pkCol = &c
			break
		}
	}

	var b strings.Builder

	b.WriteString("// Code generated by SupaGo. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", table.Name))

	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"fmt\"\n\n")
	b.WriteString("\t\"github.com/jackc/pgx/v5/pgxpool\"\n")
	b.WriteString(fmt.Sprintf("\t\"%s\"\n", modelsPkg))
	b.WriteString(")\n\n")

	b.WriteString(fmt.Sprintf("type Repository struct {\n\tpool *pgxpool.Pool\n}\n\n"))
	b.WriteString(fmt.Sprintf("func NewRepository(pool *pgxpool.Pool) *Repository {\n\treturn &Repository{pool: pool}\n}\n\n"))

	// List
	b.WriteString(fmt.Sprintf("func (r *Repository) List(ctx context.Context) ([]%s.%s, error) {\n", filepath.Base(modelsPkg), structName))
	b.WriteString(fmt.Sprintf("\trows, err := r.pool.Query(ctx, \"SELECT %s FROM %s\")\n", colNames, table.Name))
	b.WriteString("\tif err != nil {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"list %s: %%w\", err)\n", table.Name))
	b.WriteString("\t}\n")
	b.WriteString("\tdefer rows.Close()\n\n")
	b.WriteString(fmt.Sprintf("\tvar items []%s.%s\n", filepath.Base(modelsPkg), structName))
	b.WriteString("\tfor rows.Next() {\n")
	b.WriteString(fmt.Sprintf("\t\tvar item %s.%s\n", filepath.Base(modelsPkg), structName))
	b.WriteString(fmt.Sprintf("\t\tif err := rows.Scan(%s); err != nil {\n", colFields))
	scanErrName := singularize(table.Name)
	b.WriteString(fmt.Sprintf("\t\t\treturn nil, fmt.Errorf(\"scan %s: %%w\", err)\n", scanErrName))
	b.WriteString("\t\t}\n")
	b.WriteString("\t\titems = append(items, item)\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn items, rows.Err()\n")
	b.WriteString("}\n\n")

	if pkCol != nil {
		pkGoType := toGoType(pkCol.DataType, false)
		pkField := toPascalCase(pkCol.Name)

		// GetByID
		b.WriteString(fmt.Sprintf("func (r *Repository) GetByID(ctx context.Context, id %s) (*%s.%s, error) {\n", pkGoType, filepath.Base(modelsPkg), structName))
		b.WriteString(fmt.Sprintf("\trow := r.pool.QueryRow(ctx, \"SELECT %s FROM %s WHERE %s = $1\", id)\n", colNames, table.Name, pkCol.Name))
		b.WriteString(fmt.Sprintf("\tvar item %s.%s\n", filepath.Base(modelsPkg), structName))
		b.WriteString(fmt.Sprintf("\tif err := row.Scan(%s); err != nil {\n", colFields))
		b.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"get %s by id: %%w\", err)\n", scanErrName))
		b.WriteString("\t}\n")
		b.WriteString("\treturn &item, nil\n")
		b.WriteString("}\n\n")

		// Create (exclude PK)
		var insertCols []string
		var insertFields []string
		for _, c := range cols {
			if c.PrimaryKey {
				continue
			}
			insertCols = append(insertCols, c.Name)
			insertFields = append(insertFields, "item."+toPascalCase(c.Name))
		}

		if len(insertCols) > 0 {
			placeholders := make([]string, len(insertCols))
			for i := range placeholders {
				placeholders[i] = fmt.Sprintf("$%d", i+1)
			}

			b.WriteString(fmt.Sprintf("func (r *Repository) Create(ctx context.Context, item *%s.%s) error {\n", filepath.Base(modelsPkg), structName))
			b.WriteString(fmt.Sprintf("\t_, err := r.pool.Exec(ctx, \"INSERT INTO %s (%s) VALUES (%s)\",\n", table.Name, strings.Join(insertCols, ", "), strings.Join(placeholders, ", ")))
			b.WriteString(fmt.Sprintf("\t\t%s,\n", strings.Join(insertFields, ",\n\t\t")))
			b.WriteString("\t)\n")
			b.WriteString("\tif err != nil {\n")
			b.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"create %s: %%w\", err)\n", scanErrName))
			b.WriteString("\t}\n")
			b.WriteString("\treturn nil\n")
			b.WriteString("}\n\n")
		}

		// Update (exclude PK)
		var setClauses []string
		var updateFields []string
		paramIdx := 1
		for _, c := range cols {
			if c.PrimaryKey {
				continue
			}
			setClauses = append(setClauses, fmt.Sprintf("%s = $%d", c.Name, paramIdx))
			updateFields = append(updateFields, "item."+toPascalCase(c.Name))
			paramIdx++
		}
		updateFields = append(updateFields, "item."+pkField)

		if len(setClauses) > 0 {
			b.WriteString(fmt.Sprintf("func (r *Repository) Update(ctx context.Context, item *%s.%s) error {\n", filepath.Base(modelsPkg), structName))
			b.WriteString(fmt.Sprintf("\t_, err := r.pool.Exec(ctx, \"UPDATE %s SET %s WHERE %s = $%d\",\n", table.Name, strings.Join(setClauses, ", "), pkCol.Name, paramIdx))
			b.WriteString(fmt.Sprintf("\t\t%s,\n", strings.Join(updateFields, ",\n\t\t")))
			b.WriteString("\t)\n")
			b.WriteString("\tif err != nil {\n")
			b.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"update %s: %%w\", err)\n", scanErrName))
			b.WriteString("\t}\n")
			b.WriteString("\treturn nil\n")
			b.WriteString("}\n\n")
		}

		// Delete
		b.WriteString(fmt.Sprintf("func (r *Repository) Delete(ctx context.Context, id %s) error {\n", pkGoType))
		b.WriteString(fmt.Sprintf("\t_, err := r.pool.Exec(ctx, \"DELETE FROM %s WHERE %s = $1\", id)\n", table.Name, pkCol.Name))
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"delete %s: %%w\", err)\n", scanErrName))
		b.WriteString("\t}\n")
		b.WriteString("\treturn nil\n")
		b.WriteString("}\n")
	}

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("format source: %w", err)
	}
	return os.WriteFile(path, src, 0644)
}

func columnNames(cols []introspection.Column) string {
	names := make([]string, len(cols))
	for i, c := range cols {
		names[i] = c.Name
	}
	return strings.Join(names, ", ")
}

func columnFields(cols []introspection.Column) string {
	fields := make([]string, len(cols))
	for i, c := range cols {
		fields[i] = "&item." + toPascalCase(c.Name)
	}
	return strings.Join(fields, ", ")
}
